### PR TITLE
Setup of the project

### LINKED ISSUE #9: Heroku Deployment
# User story
As a **developer**, 
I want to create a deployment on Heroku
so that everybody can review my project in real time

## Notes / Links
```npm init -y```
```npm install express``` - https://expressjs.com/es/starter/hello-world.html
Create a new pipeline on Heroku - https://dashboard.heroku.com/pipelines/new

## Acceptance criteria 

- [x] Create the package.json 
- [x] Install ExpressJS and set it in server.js
- [x] Create new pipeline and new App on Heroku
- [x] Automatic deploy branch (master)

### PR DESCRIPTION
**Pull request by manuelsanchez2**
## Setup of the project

The project is created from scratch with MIT License, .gitignore and README.md.
We run ```npm init -y``` to have the package.json and add MIT Licence and "private": true.

In this pull request we complete the Heroku deployment (closes #9)  after linking the GitHub repository and setting up the automatic deployment.

### CODE REVIEW

**Comment by mskradde** [comment]
good Job!

**Comment by DrBennemin** [comment]
wow. looks good

**Review by slawoe — APPROVED** [review]
lgtm

**Review by manuelpapa — APPROVED** [review]
Now we talking bro

**Pull request merged**
